### ISSUE TITLE
Another approach to summary

### ISSUE THREAD

**Issue by datawookie** [MeganBeckett/lubridate-heatmaps_tutorial#1]
You can also use `summarytools` package.

```
library(summarytools)

dfSummary(app_train)
#
# This will create output in the Viewer window. Pop that out to view in browser.
#
view(dfSummary(app_train))
```

**Comment by MeganBeckett** [comment]
Thanks! This is great - the histograms are really nice - much better than skim(). I also added the summarytools.css so that the html output works better with Rmarkdown. The documentation says that they are working on imporving the html rendering, as it's not as neat as it could be.
